Albert byrone/tf 31/firebase login
sinatra-pod/the-force pull request #11
Opened 2023-01-31 08:43 UTC by Albert-Byrone

Add Google login with firebase

2023-01-31 12:49 UTC, otsembo requested changes

2023-01-31 12:49 UTC, otsembo commented on src/views/Login.tsx
> +        console.log(user)
Hello @Albert-Byrone Kindly remove unnecessary console logs.

2023-01-31 12:49 UTC, otsembo commented on src/utils/firebase.ts
> +console.log(firebaseConfig)
Remove unnecessary logs

2023-01-31 12:58 UTC, otsembo approved these changes
Great Job @Albert-Byrone

2023-02-02 06:05 UTC, mutuajoseph approved these changes

2023-02-06 05:58 UTC, merged